
name: Deploy to Azure CDN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Install Azure CLI
      #   uses: azure/CLI@v1
      #   with:
      #     azcliversion: latest
          # inlineScript: |
          #   az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      #   with:
      #     azcliversion: latest
      - name: Install Azure CLI
        run: |
          sudo apt-get update && sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update && sudo apt-get install -y azure-cli=2.28.0
          
      - name: Azure login
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload website files to Azure Storage Account
        run: az storage blob upload-batch --account-name storageforcicdobject --destination \$web --source "C:/Users/DELL/OneDrive/Desktop/VirtueCloud/Azure-task/" --no-progress

      - name: Configure CDN endpoint
        run: |
          az cdn endpoint create --name Cdn-endpoint-name1cicd --profile-name CDN-profile1forcicd --origin storageforcicdobject.z13.web.core.windows.net --origin-host-header storageforcicdobject.z13.web.core.windows.net --resource-group ankit-resource-group --cdn-type Standard_Verizon
