
name: Deploy to Azure CDN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Azure CLI
        uses: AzureCLI@1
        with:
          azcliversion: latest

      - name: Azure login
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload website files to Azure Storage Account
        run: az storage blob upload-batch --account-name storageforcicdobject --destination \$web --source "C:/Users/DELL/OneDrive/Desktop/VirtueCloud/Azure-task/" --no-progress

      - name: Configure CDN endpoint
        run: |
          az cdn endpoint create --name Cdn-endpoint-name1cicd --profile-name CDN-profile1forcicd --origin storageforcicdobject.z13.web.core.windows.net --origin-host-header storageforcicdobject.z13.web.core.windows.net --resource-group ankit-resource-group --cdn-type Standard_Verizon
